steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/niveusgcp/cloud-like:${SHORT_SHA}', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/niveusgcp/cloud-like']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta','run','deploy','cloud-like', '--image', 'gcr.io/niveusgcp/cloud-like:${SHORT_SHA}', '--region', 'us-central1', '--quiet']



